{% set name = "TraffiX" %}
{% set version = "0.1.0a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/TraffiX-{{ version }}.tar.gz
  sha256: cf76ce8d904b7543530b32c779b61e81dbd55356848e660370279848e1d00bbc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - osmnx >=1.3.0,<1.4.dev0
    - pandas >=1.2.4,<1.3.dev0

test:
  imports:
    - TraffiX
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Ultios/StraPy
  summary: A package for macroscopic transportation assignment.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ultios
